name: Documentation improvement
title: "Docs: "
description: Report a documentation problem or suggest an improvement
labels: ["documentation"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or topic
    validations:
      required: true

  - type: textarea
    id: improve
    attributes:
      label: Proposed change
    validations:
      required: true
