name: Feature request
title: "Feature: "
description: Suggest a new aioarxiv feature
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem would this feature solve?
    validations:
      required: true

  - type: textarea
    id: feature
    attributes:
      label: Proposed feature
      description: Describe the feature or solution you would like
    validations:
      required: true
