name: Setup Python
description: Setup Python

inputs:
  python-version:
    description: Python version
    required: false
    default: "3.10"
  env-dir:
    description: Environment directory
    required: false
    default: "."
  no-root:
    description: Do not install package in the environment
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install pdm
      run: pipx install pdm
      shell: bash

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pdm"
        cache-dependency-path: |
          ./pdm.lock
          ${{ inputs.env-dir }}/pdm.lock

    - run: |
        cd ${{ inputs.env-dir }}
          pdm install --all
        fi
      shell: bash
