name: Pyright Lint

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "envs/**"
      - "aioarxiv/**"
      - "tests/**"
      - ".github/actions/setup-python/**"
      - ".github/workflows/pyright.yml"
      - "pyproject.toml"
      - "pdm.lock"

jobs:
  pyright:
    name: Pyright Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11", "3.12" ]
      fail-fast: false
    concurrency:
      group: pyright-${{ github.ref }}-${{ matrix.python-version }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}
          with-groups: "test,dev"
          no-root: "false"

      - name: Run Pyright
        uses: jakebailey/pyright-action@v2
        with:
          pylance-version: "latest-release"
          use-config: true
          working-directory: "."
          extra-args: "--warnings --verbose"
          annotate: true