name: Ruff Lint

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "aioarxiv/**"
      - "tests/**"
      - ".github/actions/setup-python/**"
      - ".github/workflows/ruff.yml"
      - "pyproject.toml"
      - "pdm.lock"

jobs:
  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    concurrency:
      group: ruff-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: ~/.cache/ruff
          key: ${{ runner.os }}-ruff-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-ruff-

      - name: Run Ruff
        uses: astral-sh/ruff-action@v1
        with:
          version: "latest"
          args: "check --fix"